# Generated by Django 5.0.7 on 2024-08-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_conversationmetrics_conversation_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='dominant_topic',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='in_reply_to',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='message_ptr',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AIMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
