# Generated by Django 5.0.8 on 2024-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SH', 'Shipped'), ('DE', 'Delivered'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
