# Generated by Django 5.0.8 on 2024-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Processing'), ('SH', 'Shipped'), ('PE', 'Pending'), ('DE', 'Delivered'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
