# Generated by Django 5.0.8 on 2024-11-18 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderconversationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='Shipping carrier (e.g., FedEx, UPS)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Shipping address for delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, help_text='Estimated delivery date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, help_text='Date when the order was shipped', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('ST', 'Standard Shipping'), ('EX', 'Express Shipping'), ('ON', 'Overnight Shipping'), ('LO', 'Local Delivery')], default='ST', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Tracking number can only contain letters, numbers, and hyphens', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this tracking update occurred')),
                ('status', models.CharField(choices=[('PL', 'Order Placed'), ('PR', 'Processing'), ('PK', 'Picked'), ('PA', 'Packed'), ('SH', 'Shipped'), ('TR', 'In Transit'), ('OD', 'Out for Delivery'), ('DE', 'Delivered'), ('FA', 'Failed Delivery Attempt'), ('EX', 'Delivery Exception'), ('RT', 'Returned to Sender')], help_text='Current tracking status', max_length=2)),
                ('location', models.CharField(blank=True, help_text='Location of the package', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about this tracking update', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='orders.order')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order', '-timestamp'], name='orders_orde_order_i_06256d_idx'), models.Index(fields=['status', 'timestamp'], name='orders_orde_status_a54e2e_idx')],
            },
        ),
    ]
