# Generated by Django 5.0.8 on 2024-11-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convochat', '0006_remove_sentiment_convochat_s_is_exam_73e29e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentimentcategory',
            options={'verbose_name_plural': 'Sentiment Categories'},
        ),
    ]
