# Generated by Django 5.0.8 on 2024-11-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convochat', '0008_aitext_tool_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_intent',
            field=models.CharField(blank=True, help_text='Current conversation intent/context', max_length=50, null=True),
        ),
    ]
