# Generated by Django 5.0.8 on 2024-09-07 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConversation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Conversation', max_length=255)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived'), ('EN', 'Ended')], default='AC', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GeneralMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('content_type', models.CharField(choices=[('TE', 'Text'), ('IM', 'Image'), ('AU', 'Audio'), ('VI', 'Video'), ('DO', 'Document')], default='TE', max_length=2)),
                ('content', models.TextField(default='No Text Data Found')),
                ('is_from_user', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_messages', to='general_assistant.generalconversation')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='general_assistant.generalmessage')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_messages/')),
                ('transcript', models.TextField()),
                ('duration', models.FloatField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_content', to='general_assistant.generalmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='generalconversation',
            index=models.Index(fields=['user', 'created'], name='general_ass_user_id_7fa62b_idx'),
        ),
        migrations.AddIndex(
            model_name='generalconversation',
            index=models.Index(fields=['status'], name='general_ass_status_edaad0_idx'),
        ),
        migrations.AddIndex(
            model_name='generalmessage',
            index=models.Index(fields=['conversation', 'created'], name='general_ass_convers_7f56f6_idx'),
        ),
        migrations.AddIndex(
            model_name='generalmessage',
            index=models.Index(fields=['is_from_user'], name='general_ass_is_from_1bf2a9_idx'),
        ),
    ]
