# Generated by Django 5.0.8 on 2024-11-21 12:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsnapshot',
            name='metrics_data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Conversation metrics at time of snapshot'),
        ),
        migrations.AlterField(
            model_name='conversationsnapshot',
            name='state_data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Complete serialized conversation state data'),
        ),
    ]
