# Generated by Django 5.0.8 on 2024-11-20 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convochat', '0009_conversation_current_intent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSnapshot',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the snapshot', primary_key=True, serialize=False)),
                ('state_data', models.JSONField(default=dict, help_text='Complete serialized conversation state data')),
                ('metrics_data', models.JSONField(default=dict, help_text='Conversation metrics at time of snapshot')),
                ('total_messages', models.PositiveIntegerField(default=0, help_text='Total number of messages at snapshot time')),
                ('user_messages', models.PositiveIntegerField(default=0, help_text='Number of user messages at snapshot time')),
                ('ai_messages', models.PositiveIntegerField(default=0, help_text='Number of AI messages at snapshot time')),
                ('intent_changes', models.PositiveIntegerField(default=0, help_text='Number of intent changes at snapshot time')),
                ('tool_uses', models.PositiveIntegerField(default=0, help_text='Number of tool uses at snapshot time')),
                ('avg_response_time', models.FloatField(blank=True, help_text='Average AI response time in seconds at snapshot time', null=True)),
                ('current_intent', models.CharField(blank=True, help_text='Current conversation intent at snapshot time', max_length=100, null=True)),
                ('previous_intent', models.CharField(blank=True, help_text='Previous conversation intent at snapshot time', max_length=100, null=True)),
                ('snapshot_type', models.CharField(choices=[('AU', 'Automatic'), ('MN', 'Manual'), ('EV', 'Event'), ('FN', 'Final')], default='AU', help_text='Type of snapshot', max_length=2)),
                ('conversation', models.ForeignKey(help_text='The conversation this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='convochat.conversation')),
            ],
            options={
                'verbose_name': 'Conversation Snapshot',
                'verbose_name_plural': 'Conversation Snapshots',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['conversation', '-created'], name='support_age_convers_9d50db_idx'), models.Index(fields=['current_intent'], name='support_age_current_148ffa_idx'), models.Index(fields=['snapshot_type'], name='support_age_snapsho_4a6392_idx')],
            },
        ),
    ]
