# Generated by Django 5.0.7 on 2024-08-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmetrics',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.conversation'),
        ),
        migrations.AddField(
            model_name='intentprediction',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.intent'),
        ),
        migrations.AddField(
            model_name='intentprediction',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent_prediction', to='dashboard.usermessage'),
        ),
        migrations.AddField(
            model_name='llmagentperformance',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='dashboard.conversation'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='dashboard.conversation'),
        ),
        migrations.AddField(
            model_name='topicdistribution',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_distributions', to='dashboard.conversation'),
        ),
        migrations.AddField(
            model_name='topicdistribution',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topicdistribution',
            unique_together={('conversation', 'topic')},
        ),
    ]
