# Generated by Django 5.0.7 on 2024-08-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
        ('convochat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmetrics',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='convochat.conversation'),
        ),
        migrations.AlterField(
            model_name='intentprediction',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convochat.intent'),
        ),
        migrations.AlterField(
            model_name='intentprediction',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent_prediction', to='convochat.usermessage'),
        ),
        migrations.AlterField(
            model_name='llmagentperformance',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='convochat.conversation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='convochat.conversation'),
        ),
        migrations.AlterField(
            model_name='topicdistribution',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_distributions', to='convochat.conversation'),
        ),
        migrations.AlterField(
            model_name='topicdistribution',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convochat.topic'),
        ),
    ]
