# Generated by Django 5.0.7 on 2024-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_conversationmetrics_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmetrics',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
