# Generated by Django 5.0.8 on 2024-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_intentprediction_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentprediction',
            name='intent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
