# Generated by Django 5.0.8 on 2024-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SH', 'Shipped'), ('TR', 'In Transit'), ('DE', 'Delivered'), ('RT', 'Returned'), ('RF', 'Refunded'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
