# Generated by Django 5.0.8 on 2024-11-09 03:20

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAGTextClassificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('SE', 'Sentiment Analysis'), ('IN', 'Intent Recognition'), ('TO', 'Topic Classification')], max_length=2)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', pgvector.django.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='playground__task_555d47_idx'), models.Index(fields=['created_at'], name='playground__created_b5cca1_idx')],
            },
        ),
    ]
