# Generated by Django 5.0.8 on 2024-11-14 18:12

import django.db.models.deletion
import general_assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_messages/', validators=[general_assistant.models.validate_image])),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('description', models.TextField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_content', to='general_assistant.generalmessage')),
            ],
        ),
    ]
