# Generated by Django 5.0.8 on 2024-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_rename_applied_recommendation_is_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentprediction',
            name='intent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
