# Generated by Django 5.0.8 on 2024-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convochat', '0002_rename_overall_sentiment_conversation_overall_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('RE', 'Resolved'), ('PR', 'In Progress'), ('UN', 'Unresolved')], default='UN', max_length=2, null=True),
        ),
    ]
