# Generated by Django 5.0.8 on 2024-11-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convochat', '0003_conversation_resolution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('PR', 'Product-Related'), ('OR', 'Order Management'), ('PA', 'Payment & Account'), ('EX', 'Customer Experience')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this topic is currently in use'),
        ),
        migrations.AddField(
            model_name='topic',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='priority_weight',
            field=models.FloatField(default=1.0, help_text='Weight factor for topic importance in analysis'),
        ),
        migrations.AddField(
            model_name='topic',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this topic was identified in conversations'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category', 'name'], name='convochat_t_categor_d09aae_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active', 'usage_count'], name='convochat_t_is_acti_ce1529_idx'),
        ),
    ]
