# Generated by Django 5.0.8 on 2024-11-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convochat', '0005_granularemotion_sentimentcategory_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sentiment',
            name='convochat_s_is_exam_73e29e_idx',
        ),
        migrations.RemoveField(
            model_name='granularemotion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='example_text',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='is_example',
        ),
        migrations.RemoveField(
            model_name='sentimentcategory',
            name='is_active',
        ),
    ]
